version: '3.2'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.dashboard=false"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.mqtt.address=:1883"
      # - "--entrypoints.mqttsecure.address=:8883"
      # Letsencrypt
      # - --certificatesresolvers.letsencrypt.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      # - --certificatesresolvers.letsencrypt.acme.email=felipecardenas301@gmail.com
      # - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "1883:1883"
      # - "8883:8883"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./letsencrypt:/letsencrypt
    restart: always

  mqtt:
    container_name: mqtt
    image: mqtt_broker
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 1883
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.purple-sheep.com`)"
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.mqtt.tls=true"
      - "traefik.tcp.routers.mqtt.tls.certresolver=letsencrypt"
    depends_on:
      - traefik
    env_file:
      - .env
