version: '3.2'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposeByDefault=false"
      - "--entrypoints.mqtt.address=:1883"
    ports:
      - "1883:1883"
      - "8883:1883"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mqtt
  mqtt:
    container_name: mqtt
    image: mqtt_broker
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 1883
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mqtt"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.tcpr_mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.tcpr_mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tcpr_mqtt.service=mqtt"
    env_file:
      - .env

networks:
  mqtt:
    driver: bridge
